repos:
- repo: local
  hooks:
  - id: trailing-whitespace
    name: trailing whitespace
    stages: [commit]
    language: system
    entry: trailing-whitespace-fixer
    types: [python]

  - id: isort
    name: import sort
    stages: [commit]
    language: system
    entry: isort
    types: [python]

  - id: black
    name: format
    stages: [commit]
    language: system
    entry: black
    types: [python]
